# Generated by Django 2.0 on 2020-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0003_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='usabilty',
            new_name='usability',
        ),
    ]
